version: '3.8'
services:

  nginx:
    image: nginx:stable
    container_name: bozaweb
    # build: 
    #   context: nginx
    ports:
      - 8080:80
    volumes:
      - $PWD/web:/usr/share/nginx/html:ro
      # - $PWD/nginx/volume:/
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      network:
        ipv4_address: 10.5.0.7

  mysql:
    image: mysql:8.0
    container_name: bozamysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=boza
      # - MYSQL_DATABASE=testdb
      # - MYSQL_USER=test
      # - MYSQL_PASSWORD=test
    restart: always
    ports:
      - '3306:3306'
    networks:
      network:
        ipv4_address: 10.5.0.6

  ubuntu20:
    image: ubuntu20-custom-image:1.0
    container_name: bozaubuntu
    build:
      context: ubuntu20-custom
    volumes:
       - $PWD/ubuntu20-custom/volume:/home/user/volume
    environment:
      - LOCAL_USER_ID=1000
    tty: true
    ports:
      - 8081:81
    networks:
      network:
        ipv4_address: 10.5.0.5

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1